apiVersion: v1
kind: DeploymentConfig
metadata:
  labels:
    app: nginx
  name: nginx
spec:
  replicas: 1
  selector:
    app: nginx
    deploymentconfig: nginx
  strategy:
    type: Rolling
  template:
    metadata:
      labels:
        app: nginx
        deploymentconfig: nginx
    spec:
      containers:
      - image: tomaskral/nonroot-nginx:latest
        imagePullPolicy: IfNotPresent
        name: nginx
        resources:
          limits:
            memory: 16Mi
        ports:
        - containerPort: 8080
          protocol: TCP
        readinessProbe:
          failureThreshold: 2
          httpGet:
            path: /
            port: 8080
            scheme: HTTP
          periodSeconds: 1
          successThreshold: 1
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
  name: nginx
spec:
  ports:
  - name: nginx-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: nginx
    deploymentconfig: nginx
  type: ClusterIP
---
apiVersion: v1
kind: Route
metadata:
  name: nginx
spec:
  port:
    targetPort: nginx-8080
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: nginx
    weight: 100